version: '3.8'

services:
  rent-scout:
    build: .
    image: rent-scout:latest
    container_name: rent-scout
    restart: unless-stopped
    ports:
      - "7777:7777"
    environment:
      - CONFIG_PATH=/app/config/config.toml
      - ENV_PATH=/app/config/config.env.local.toml
      - DB_PATH=/app/db/rent-scout.db
    volumes:
      - ./config:/app/config
      - ./data:/app/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
